spring.application.name=E-Commerce-Shop
server.port=8080
server.error.include-message=always
#formats the logs
spring.output.ansi.enabled=always

#DB details
#url catre baza de date
spring.datasource.url=jdbc:postgresql://localhost:5432/Shop1
spring.datasource.username=developer
spring.datasource.password=BogdanMdl1
#ii spunem ce driver sa foloseasca pt a comunica cu baza de date
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.serialization.write-dates-as-timestamps=false

spring.jpa.properties.hibernate.format_sql=true


# SMTP Mailtrap configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=roxen.029@gmail.com
spring.mail.password=vpnl nadx abls obdy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#pt plata
stripe.secret.key=sk_test_51R88Q2FsIVGXG6aQezIcDs6YkX47gjtfxMsMMSSVU7yQIziVwKi208DKihAasSPQv2bb5UpkglFqqpMx62RH0A15004zlvbqoW
stripe.public.key=pk_test_51R88Q2FsIVGXG6aQ0yfJPTfjUGZT1vTfQWrsFG7bSZ89egnNHRI0TupuPFrb3pDeSjEV2az7eLphd354nB6InWB400Oz1tucyT


#chatbot
openai.api.key=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